---
- name: BASIC TASKS
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Ensure ansible user doesn't exists
      user:
        name: ansible
        state: absent

    - name: Test host connectivity
      ping:
